### ISSUE TITLE
PassthroughClientDescriptor can not be serialized

### ISSUE THREAD

**Issue by albinsuresh** [Terracotta-OSS/tc-passthrough-testing#124]
Even though the `ClientDescriptor` interface is `Serializable`, the `PassthroughClientDescriptor` class is not serializable because of the non-transient `PassthroughServerProcess` and `PassthroughConnection` fields in it.

Serialization attempts cause this exception:
```java
Caused by: java.lang.RuntimeException: Failed to serialize : PassthroughClientDescriptor{server=org.terracotta.passthrough.PassthroughServerProcess@2339147a,org.terracotta.passthrough.PassthroughConnection@2d3379b4,clientInstanceID=3}
	at com.terracottatech.store.common.ByteBufferUtil.serialize(ByteBufferUtil.java:27)
	at com.terracottatech.store.common.messages.replication.CRUDDataReplicationMessage.encode(CRUDDataReplicationMessage.java:81)
	at com.terracottatech.store.common.messages.ClientServerMessageType.encode(ClientServerMessageType.java:84)
	at com.terracottatech.store.common.messages.DatasetMessageCodec.encodeMessage(DatasetMessageCodec.java:114)
	... 25 more
Caused by: java.io.NotSerializableException: org.terracotta.passthrough.PassthroughConnection
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.terracottatech.store.common.ByteBufferUtil.serialize(ByteBufferUtil.java:25)
	... 28 more
```

**Comment by ramsai1729** [comment]
Looks like PassthroughClientDescriptor is not correct for passive invocation as well, will investigate and create an issue if needed. 

  // Invoke on passive.
      CreationData<?, ?> data = this.passiveEntities.get(entityTuple);
      if (null != data) {
        PassthroughClientDescriptor clientDescriptor = new PassthroughClientDescriptor(this, null, clientInstanceID);

        // There is no return type in the passive case.
        sendPassiveInvocation(entityClassName,
                              entityName,
                              clientDescriptor,
                              transactionId,
                              eldestTransactionId,
                              data,
                              payload);
      } else {
        throw new EntityNotFoundException(entityClassName, entityName);
      }

**Comment by ramsai1729** [comment]
created an issue #129 for tracking PassthroughClientDescriptor issue mentioned above
