### ISSUE TITLE
java.lang.ClassNotFoundException: com.terracottatech.licensing.client.LicenseEntity

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/tc-passthrough-testing#191]
With dynamic config, we have some server entities that are permanent but are not meant to be consumed by an clients: they are used to add some behaviors when a server is active or passive.

```
java.lang.ClassNotFoundException: com.terracottatech.licensing.client.LicenseEntity
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.terracottatech.licensing.client.LicenseEntity
	at org.terracotta.passthrough.PassthroughServer.addPermanentEntities(PassthroughServer.java:189)
	at org.terracotta.passthrough.PassthroughClusterControl.bootstrapCluster(PassthroughClusterControl.java:211)
	at org.terracotta.passthrough.PassthroughClusterControl.<init>(PassthroughClusterControl.java:63)
	at org.terracotta.passthrough.PassthroughTestHelpers.createMultiServerStripe(PassthroughTestHelpers.java:71)
	at com.terracottatech.testing.AbstractEnterprisePassthroughTest._before(AbstractEnterprisePassthroughTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.terracottatech.licensing.client.LicenseEntity
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.terracotta.passthrough.PassthroughServer.addPermanentEntities(PassthroughServer.java:187)
	... 52 more
```

Some tests are now failing because The `PassthroughServer` class line 187 expect the String type of an entity to be a `Class`, whereas the API does not enforce that.

```
  public void addPermanentEntities() {
    // Populate the server with its services.
    for (EntityServerService<?, ?> serverEntityService : this.savedServerEntityServices) {
      if (serverEntityService.getClass().isAnnotationPresent(PermanentEntity.class)) {
        PermanentEntity pe = serverEntityService.getClass().getAnnotation(PermanentEntity.class);
        String type = pe.type();
        String[] names = pe.names();
        int version = pe.version();
        for (String name : names) {
          try {
            pseudoConnection.getEntityRef((Class)Class.forName(type), (long)version, name).create(null);
          } catch (ClassNotFoundException not) {
            throw new RuntimeException(not);
          } catch (EntityException exp) {
            throw new RuntimeException(exp);
          }
        }
      }
    }
```

`LicenseEntityService` is defined as follow and `LicenseEntity` does not exist anymore.

```
@PermanentEntity(type = "com.terracottatech.licensing.client.LicenseEntity", names = {"license-entity"})
public class LicenseEntityService implements EntityServerService<EntityMessage, EntityResponse> {
```

**Comment by myronkscott** [comment]
While I am looking at this your quickest path forward is to add an empty class or interface for LicenseEntity

**Comment by saurabhagas** [comment]
@myronkscott, for now, I managed to work around the bug by introducing an empty `LicenseEntity`. The issue would need to be fixed though. Please let me know if you're fixing it, or you want me to fix it. If it's the latter, let me know your thoughts on how to go about the fix.

**Comment by myronkscott** [comment]
PermanentEntityType is the recommended use going forward rather than PermanentEntity.  It uses classes as types rather than Strings. I will add support for this annotation.

**Comment by mathieucarbou** [comment]
> PermanentEntityType is the recommended use going forward rather than PermanentEntity. It uses classes as types rather than Strings. I will add support for this annotation.

I don't understand... So now, it is recommended to have client-side libraries on server classpath ?

The entity class would extend `Entity` which is in the connection api lib.

Usually, we split entities in client/common/server modules where the entity class (interface) sits in client module.

**Comment by myronkscott** [comment]
yes.  that looks like a problem.  I'll look for possible solutions to that.

**Comment by saurabhagas** [comment]
@myronkscott, I ran the passthrough tests with the the latest release (pre11, which contains this fix). Now, I get:

```
org.terracotta.exception.EntityNotProvidedException: Entity: com.terracottatech.licensing.client.LicenseEntity:license-entity no provider found for class
java.lang.RuntimeException: org.terracotta.exception.EntityNotProvidedException: Entity: com.terracottatech.licensing.client.LicenseEntity:license-entity no provider found for class
	at org.terracotta.passthrough.PassthroughServer.addPermanentEntities(PassthroughServer.java:190)
	at org.terracotta.passthrough.PassthroughClusterControl.bootstrapCluster(PassthroughClusterControl.java:211)
	at org.terracotta.passthrough.PassthroughClusterControl.<init>(PassthroughClusterControl.java:63)
	at org.terracotta.passthrough.PassthroughTestHelpers.createMultiServerStripe(PassthroughTestHelpers.java:71)
	at com.terracottatech.testing.AbstractEnterprisePassthroughTest._before(AbstractEnterprisePassthroughTest.java:43)
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.terracotta.exception.EntityNotProvidedException: Entity: com.terracottatech.licensing.client.LicenseEntity:license-entity no provider found for class
	at org.terracotta.passthrough.PassthroughEntityRef.create(PassthroughEntityRef.java:126)
	at org.terracotta.passthrough.PassthroughServer.addPermanentEntities(PassthroughServer.java:188)
	... 53 more
```

Since the entity doesn't exist, there can't be a provider for it..
