### ISSUE TITLE
IStripeMonitoring is not retrieved only by consumer 0

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/tc-passthrough-testing#36]
As @jd0-sag  explained me, `IStripeMonitoring` is only retrieved by the platform (__consumer id 0__). This behavior is not true in passthrough. I get the following stacktrace:

```
java.lang.AssertionError: Unexpected exception
	at org.terracotta.passthrough.Assert.unexpected(Assert.java:28)
	at org.terracotta.passthrough.PassthroughEntityRef.create(PassthroughEntityRef.java:108)
	at org.terracotta.management.entity.monitoring.client.MonitoringServiceEntityFactory.create(MonitoringServiceEntityFactory.java:59)
	at org.terracotta.management.entity.monitoring.client.MonitoringServiceEntityFactory.retrieveOrCreate(MonitoringServiceEntityFactory.java:41)
	at org.terracotta.management.entity.monitoring.MonitoringServiceProxyTest.test_read_tree(MonitoringServiceProxyTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.terracotta.exception.EntityUserException: Entity: org.terracotta.management.entity.monitoring.client.MonitoringServiceProxyEntity:MonitoringServiceProxyTest exception in user code: Unable to provide service org.terracotta.monitoring.IStripeMonitoring to consumerID: 1
	at org.terracotta.passthrough.PassthroughServerMessageDecoder.decode(PassthroughServerMessageDecoder.java:109)
	at org.terracotta.passthrough.PassthroughServerMessageDecoder.decode(PassthroughServerMessageDecoder.java:37)
	at org.terracotta.passthrough.PassthroughMessageCodec.runRawDecoder(PassthroughMessageCodec.java:344)
	at org.terracotta.passthrough.PassthroughMessageCodec.decodeRawMessage(PassthroughMessageCodec.java:267)
	at org.terracotta.passthrough.PassthroughServerProcess.serverThreadHandleMessage(PassthroughServerProcess.java:463)
	at org.terracotta.passthrough.PassthroughServerProcess.runServerThread(PassthroughServerProcess.java:439)
	at org.terracotta.passthrough.PassthroughServerProcess.access$000(PassthroughServerProcess.java:76)
	at org.terracotta.passthrough.PassthroughServerProcess$2.run(PassthroughServerProcess.java:213)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Unable to provide service org.terracotta.monitoring.IStripeMonitoring to consumerID: 1
	at org.terracotta.management.service.monitoring.MonitoringServiceProvider.getService(MonitoringServiceProvider.java:80)
	at org.terracotta.passthrough.PassthroughServiceRegistry.getExternal(PassthroughServiceRegistry.java:96)
	at org.terracotta.passthrough.PassthroughServiceRegistry.getService(PassthroughServiceRegistry.java:75)
	at org.terracotta.passthrough.PassthroughMonitoringProducer.getUnderlyingService(PassthroughMonitoringProducer.java:106)
	at org.terracotta.passthrough.PassthroughMonitoringProducer.getService(PassthroughMonitoringProducer.java:71)
	at org.terracotta.passthrough.PassthroughServiceRegistry.getBuiltIn(PassthroughServiceRegistry.java:87)
	at org.terracotta.passthrough.PassthroughServiceRegistry.getService(PassthroughServiceRegistry.java:74)
	at org.terracotta.management.service.monitoring.MonitoringServiceConfiguration.lambda$getMonitoringProducer$1(MonitoringServiceConfiguration.java:44)
	at java.util.Optional.map(Optional.java:215)
	at org.terracotta.management.service.monitoring.MonitoringServiceConfiguration.getMonitoringProducer(MonitoringServiceConfiguration.java:44)
	at org.terracotta.management.service.monitoring.DefaultStripeMonitoring.lambda$getOrCreateMonitoringService$12(DefaultStripeMonitoring.java:381)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at org.terracotta.management.service.monitoring.DefaultStripeMonitoring.getOrCreateMonitoringService(DefaultStripeMonitoring.java:378)
	at org.terracotta.management.service.monitoring.MonitoringServiceProvider.getService(MonitoringServiceProvider.java:73)
	at org.terracotta.passthrough.PassthroughServiceRegistry.getExternal(PassthroughServiceRegistry.java:96)
	at org.terracotta.passthrough.PassthroughServiceRegistry.getService(PassthroughServiceRegistry.java:75)
	at org.terracotta.management.entity.monitoring.server.MonitoringServiceEntityServerService.createActiveEntity(MonitoringServiceEntityServerService.java:35)
	at org.terracotta.management.entity.monitoring.server.MonitoringServiceEntityServerService.createActiveEntity(MonitoringServiceEntityServerService.java:28)
	at org.terracotta.voltron.proxy.server.ProxyServerEntityService.createActiveEntity(ProxyServerEntityService.java:83)
	at org.terracotta.passthrough.PassthroughServerProcess$CreationData.<init>(PassthroughServerProcess.java:1062)
	at org.terracotta.passthrough.PassthroughServerProcess.createAndStoreEntity(PassthroughServerProcess.java:1017)
	at org.terracotta.passthrough.PassthroughServerProcess.create(PassthroughServerProcess.java:652)
	at org.terracotta.passthrough.PassthroughServerMessageDecoder.decode(PassthroughServerMessageDecoder.java:104)
	... 8 more
```

This stacktrace is thrown when a server entity is requesting `IMonitoringProducer`. The platform requests behind an `IStripeMonitoring` with the consumer id of the entity, which is wrong. There should be one `IMonitoringProducer` per entity requesting it, and only one `IStripeMonitoring` requested by the platform.

Note: blocking PR Terracotta-OSS/terracotta-platform#161

**Comment by mathieucarbou** [comment]
I think the bug is in `PassthroughMonitoringProducer` line 59:

`final IStripeMonitoring underlying = this.getUnderlyingService(entityClassName, entityName, consumerID, container);`

1. The `consumerID` should be 0 (platform)
2. I am not sure if `IStripeMonitoring` should be retrieved for each request to `IMonitoringProducer`... My guess is that it should be retrieved once and only once by the platform, and passed to the `PassthroughMonitoringProducer` instance when constructed.

**Comment by mathieucarbou** [comment]
Talked to @myronkscott : so __the thing we really want to avoid actually is an entity requesting this `IStripeMonitoringService`__.

So currently we do a check within our provider for that, but as Myron pointed out, perhaps it would be better to have this sort of check at the platform level, with the concept of "private" services, that could only be requested by platform. Because none is prevented from implementing its own `IStripeMonitoringService` provider instead of ours and allow any entity to request a `IStripeMonitoringService`. So that's why this check could be done at the platform level.

**Comment by myronkscott** [comment]
In looking at the code further, it looks like the suggested fix above or some variant there in (only using consumerID = 0 to fetch the service) would work since the underlying collector is only ever used but the active.  I'm not sure if this is proper, however, and may have some consequence that I am failing to think about.  See terracotta-apis#161

**Comment by jd0-sag** [comment]
`IStripeMonitoring` _can_ be requested by any `consumerID`.  The only restriction and special-case surrounding `consumerID` 0 is the one listed in the JavaDoc around `serverDidBecomeActive()` and `serverDidJoinStripe()`.  Everything else is still called for the corresponding `consumerID` as the originating `IMonitoringProducer` call on the server where the call was issued.  Otherwise, there would be no way of knowing who had issued the call.

I don't know if it we need to put extra work into restricting access to any services since this one can't be used by something other than the platform in any meaningful way, anyway, since it has no `PlatformServer` instance.  That said, nothing prevents a nefarious entity from instantiating a bogus one and passing it in but I am not sure if we care about that case since a nefarious entity could do far worse things than consumer the monitoring layer.

**Comment by mathieucarbou** [comment]
@jd0-sag : what then if an entity is calling `pushbestEffort` method or `addNode` with a sender that has been "created", right or wrong, plus some data ?

1. how the implementation should behave ?
2. how we can validate the reliability of the parameters ? especially the first one ?
3. how we can make sure that an entity won't mess up the topology behind by doing some stupid calls
4. how we can make sure an entity do not use `IStripeMonitoring` (data does not get to the active) but instead `IMonitoringProducer` (data gets to the active) ?

It feels wrong to me to allow this, and i am pretty sure this is not what we discussed. You always told that `IStripeMonitoring` would always be only requested by the platform (consumer id 0) since it is a special service serving used as a sort of callbacks, and entities should use `IMonitoringProducer` instead. This was the goal when splitting into 2 interfaces also, to make passive => active works. So I don't understand your new point when you say that finally the rule only applies to some methods ? Why not the other ones ? All methods are basically callbacks triggers after an event from the platform or from an event originated by a call to `IMonitoringProducer`.

It has some implication on the M&M code behind. So we would need to have answers to that 4 questions so that the code can be reliable and can work as expected, and also so that method calls gets called by the expected callers.

Let us know how we can make sure we can prevent any "stupid" use of the service then ;-)

Thanks!

CC @anthonydahanne

**Comment by jd0-sag** [comment]
The reason why `consumerID` 0 is special in the case of those 2 methods is because the platform needs a way to describe the lifecycles of the `PlatformServer` objects used to determine which server is the origin of a call.  All the methods called in response to `IMonitoringProducer` calls come through on the same `consumerID` where they originated.

The thing which is a bit odd about this is that the `consumerID` is scoped per-server, not per-stripe, so an `IStripeMonitoring` implementation needs to be aware of this (not a huge problem, just a little odd).

I don't see the reason for the concerns that there are invalid calls being made directly to `IStripeMonitoring`, from the entity.  It seems hard to do that, by accident, when the caller would be missing the `PlatformServer` arguments all the methods required.

If we can come up with a good way to define the restriction, it might be worth doing.  I just don't see the urgency.

**Comment by mathieucarbou** [comment]
The TMS / TMC's reliability lies on the fact that the monitroing tree __is reliable__ and does not have any inconsistencies. It displays the topology.

And what is true is that any user can define its own entity.

So we __need__ a mechanism to make sure the TMS / TMC is not impacted by an entity directly using the IStripeMonitoring interface.

Othewise, what we, m&m team, could tell if there's a bug somewehre ? It could be cause by this sort of direct call.

PlatformServer object can be crafted and created by the caller: their equality is not based on `==` but on `.equals`, so anybody can create its own instance to bypass the voltron platform.

**Comment by jd0-sag** [comment]
Nefarious entities have generally not been considered a priority concern since such an entity could do far worse than confusing M&M.  They are running in a deeply trusted area.
