### ISSUE TITLE
Monitoring tree is not made aware of the new entity after entity creation and before createNew()

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/tc-passthrough-testing#50]
stack trace:

```
Caused by: java.lang.IllegalStateException: Illegal monitoring topology state: Missing consumer ID: 1 on server server-1
- currentActive: server-1
- cluster:
{stripes=[{id=SINGLE, name=SINGLE, servers=[{id=server-1, serverEntities=[], serverName=server-1, hostName=localhost, hostAddress=127.0.0.1, bindAddress=0.0.0.0, bindPort=9510, groupPort=9610, state=ACTIVE, version=Version Passthrough 5.0.0-SNAPSHOT, buildId=Build ID - -930394586, startTime=1479351689542, upTimeSec=0, activateTime=1479351689542}]}], clients=[{id=30439@127.0.0.1:UNKNOWN:e8fa604e-ea97-4b5f-87e6-bd268b4fb20d, pid=30439, hostAddress=127.0.0.1, name=UNKNOWN, logicalConnectionUid=e8fa604e-ea97-4b5f-87e6-bd268b4fb20d, vmId=30439@127.0.0.1, clientId=30439@127.0.0.1:UNKNOWN:e8fa604e-ea97-4b5f-87e6-bd268b4fb20d, hostName=matc.local, tags=[], connections=[{id=e8fa604e-ea97-4b5f-87e6-bd268b4fb20d:SINGLE:server-1:127.0.0.1:49152, logicalConnectionUid=e8fa604e-ea97-4b5f-87e6-bd268b4fb20d, clientEndpoint={address=127.0.0.1, port=49152}, stripeId=SINGLE, serverId=server-1, serverEntityIds={}}], managementRegistry=null}]}
- monitoring services:DefaultMonitoringService{
consumerId={}, 
fetches={}, 
calls={}}
	at org.terracotta.management.service.monitoring.DefaultListener.newIllegalTopologyState(DefaultListener.java:467)
	at org.terracotta.management.service.monitoring.DefaultListener.getServerEntity(DefaultListener.java:439)
	at org.terracotta.management.service.monitoring.DefaultListener.setState(DefaultListener.java:341)
	at org.terracotta.management.service.monitoring.DataListenerAdapter.addNode(DataListenerAdapter.java:60)
	at org.terracotta.passthrough.PassthroughMonitoringProducer.addNodeFromShim(PassthroughMonitoringProducer.java:123)
	at org.terracotta.passthrough.PassthroughMonitoringProducer.access$000(PassthroughMonitoringProducer.java:36)
	at org.terracotta.passthrough.PassthroughMonitoringProducer$1.addNode(PassthroughMonitoringProducer.java:81)
	at org.terracotta.management.service.monitoring.DefaultMonitoringService.exposeServerEntityManagementRegistry(DefaultMonitoringService.java:328)
	at org.terracotta.management.service.monitoring.DefaultConsumerManagementRegistry.refresh(DefaultConsumerManagementRegistry.java:78)
	at org.terracotta.management.entity.tms.server.TmsAgentImpl.init(TmsAgentImpl.java:167)
	at org.terracotta.management.entity.tms.server.TmsAgentServerEntity.createNew(TmsAgentServerEntity.java:40)
	at org.terracotta.passthrough.PassthroughServerProcess.create(PassthroughServerProcess.java:704)
	at org.terracotta.passthrough.PassthroughServerMessageDecoder.decode(PassthroughServerMessageDecoder.java:104)
	... 8 more
```

It crashed into 

```
org.terracotta.passthrough.PassthroughServerProcess.create(PassthroughServerProcess.java:704)
```

Because the `PlatformEntity` object has not been sent to the monitoring tree between the call to `createActiveEntity()` and `createNew()`

**Comment by mathieucarbou** [comment]
This is blocking:

- https://github.com/Terracotta-OSS/terracotta-platform/issues/179
- https://github.com/ehcache/ehcache3/issues/1609

**Comment by myronkscott** [comment]
Do you have a failing test case that I can use to verify the fix?

**Comment by mathieucarbou** [comment]
No it's in development (local). But soon yes I will be able to open a PR and you'll be able to run the test. It will be on tc-platform project.

**Comment by mathieucarbou** [comment]
But @myronkscott : would it possible for you n the meantime to verify that IStripeMonitoring.addNode is called wit hthe new PlatformEntity object after the creation of the entity but before the call to createNew() its made ?
Thanks!

**Comment by jd0-sag** [comment]
Is this problem an inconsistency with core, documented behavior, or a request for a specific ordering not otherwise specified?

I vaguely recall core's ordering around these operations being recently changed to accommodate a request so I just want to make sure that we are clear on the consistency between core and passthrough.

**Comment by mathieucarbou** [comment]
core seems to do the things right since we would already have seen exceptions during Ehcache system tests.
Now, we are using createNew() also in TMS Entity, tested with passthrough in tc-platform. And it does not work.

**Comment by mathieucarbou** [comment]
UPDATE for @myronkscott and @jd0-sag 👍 

The bug is in PassthroughServerProcess.create():

```
    newEntity.createNew();
    PassthroughServerProcess.EntityData data = new PassthroughServerProcess.EntityData(null);
    data.className = entityClassName;
    data.version = version;
    data.entityName = entityName;
    data.configuration = serializedConfiguration;
    this.persistedEntitiesByConsumerIDMap.put(Long.valueOf(consumerID1), data);

    try {
      this.platformPersistence.storeDataElement("entities.map", this.persistedEntitiesByConsumerIDMap);
    } catch (IOException var17) {
      Assert.unexpected(var17);
    }

    if(null != this.serviceInterface) {
      boolean isActive = null != this.activeEntities;
      PlatformEntity record = new PlatformEntity(entityClassName, entityName, consumerID1, isActive);
      String entityIdentifier = this.entityIdentifierForService(entityClassName, entityName);
      this.serviceInterface.addNode(PlatformMonitoringConstants.ENTITIES_PATH, entityIdentifier, record);
    }
```

`newEntity.createNew();` is called BEFORE `      this.serviceInterface.addNode(PlatformMonitoringConstants.ENTITIES_PATH, entityIdentifier, record);`

You can reproduce by checkouting my work branch: https://github.com/mathieucarbou/terracotta-platform/tree/issue-179 and then run `TmsAgentTest`.

**Comment by mathieucarbou** [comment]
UPDATE: this linked to https://github.com/Terracotta-OSS/terracotta-apis/issues/165. You told me to use createNew() for my needs. So I assume, and we need, to have the topology updated right after the entity is created, and __BEFORE__ and callback to "initialize" it.

Otherwise, we need this init() method that we asked for.
