### ISSUE TITLE
Construction of passthrough test randomly fails

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/tc-passthrough-testing#62]
```
java.lang.AssertionError: org.terracotta.exception.EntityNotProvidedException: Entity: org.terracotta.management.entity.tms.client.TmsAgentEntity:HAFeaturesTest no provider found for class

	at org.terracotta.management.entity.tms.client.TmsAgentEntityFactory.create(TmsAgentEntityFactory.java:70)
	at org.terracotta.management.entity.tms.client.TmsAgentEntityFactory.retrieveOrCreate(TmsAgentEntityFactory.java:45)
	at org.terracotta.management.entity.sample.AbstractTest.connectManagementClients(AbstractTest.java:217)
	at org.terracotta.management.entity.sample.AbstractTest.setUp(AbstractTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.terracotta.exception.EntityNotProvidedException: Entity: org.terracotta.management.entity.tms.client.TmsAgentEntity:HAFeaturesTest no provider found for class
	at org.terracotta.passthrough.PassthroughEntityRef.create(PassthroughEntityRef.java:114)
	at org.terracotta.management.entity.tms.client.TmsAgentEntityFactory.create(TmsAgentEntityFactory.java:67)
	... 31 more
```

It fails fast in the setup method.

Just open `HAFeaturesTest` and run it, or just `get_notifications_when_passive_joins`. It randomly fails with this exception.

Test and branch:

https://github.com/mathieucarbou/terracotta-platform/blob/739f9d65deef22a31f4178f7e4b2d522547464ef/management/testing/sample-entity/src/test/java/org/terracotta/management/entity/sample/ha/HAFeaturesTest.java#L37-L37

**Comment by mathieucarbou** [comment]
CC @anthonydahanne @GaryWKeim

**Comment by myronkscott** [comment]
This is due to improper test setup.  You need to configure each server in your stripe.

PR raised against your test code mathieucarbou/terracitta-platform#2
