### ISSUE TITLE
Passthrough does not call sync methods

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/tc-passthrough-testing#63]
`HAFeaturesTest.passives_can_sync_data_on_start`

https://github.com/mathieucarbou/terracotta-platform/blob/dfd6f72b3b5cfe37654fac64514b0600b4e8cd0f/management/testing/sample-entity/src/test/java/org/terracotta/management/entity/sample/ha/HAFeaturesTest.java#L71-L71

I am expecting to see some values syncing from active to passive and some logs proving we went into:

`PassiveServerEntity.startSyncEntity()` and `PassiveServerEntity.endSyncEntity()`

But I got nothing. Not management notifications also.

__Also blocks PR: https://github.com/Terracotta-OSS/terracotta-platform/pull/229__

**Comment by mathieucarbou** [comment]
looking further, calls are made to: `channel.synchronizeToPassive(m);` but not received into `PassiveServerEntity.invoke(m)`

**Comment by myronkscott** [comment]
Confirmed to be working.  Not a bug

**Comment by mathieucarbou** [comment]
I updated Terracotta-OSS/terracotta-platform#229.

I put a BP into these places but I never go there.

- `PassiveProxiedServerEntity.invole()`
- `PassiveCacheServerEntity.startSyncEntity`
- `PassiveCacheServerEntity.endSyncEntity`
- `PassiveCacheServerEntity.startSyncConcurrencyKey`
- `PassiveCacheServerEntity.endSyncConcurrencyKey`

I go into `ActiveCacheServerEntity.synchronizeKeyToPassive` and `channel.synchronizeToPassive(proxyEntityMessage);` is called (`SyncProxyFactory` line 44).

Test: https://github.com/mathieucarbou/terracotta-platform/blob/5388bcc6bdf886baaa50f20064366ef2cbbea99d/management/testing/sample-entity/src/test/java/org/terracotta/management/entity/sample/ha/HATests.java#L93-L93

I should have some notifications about SYNC_START / SYNC_END and the passive entity should receive sync invocations. I don't understand why it does not received them.

By debugging, I saw the sync message is created an but into the message queue in `PassthroughServerProcess`, but the invoke() is not called on passive.

It is possible that some setup is wrong about proxy or our entities or concurrency keys perhaps...

**Comment by myronkscott** [comment]
Your passive is failing to create at the start of sync.  Fix this and you should see the messages flowing.  
```
java.lang.IllegalStateException: Server server1 is not passive!
	at org.terracotta.management.service.monitoring.MonitoringServiceProvider.getService(MonitoringServiceProvider.java:217)
	at org.terracotta.passthrough.PassthroughServiceRegistry.getExternal(PassthroughServiceRegistry.java:104)
	at org.terracotta.passthrough.PassthroughServiceRegistry.getService(PassthroughServiceRegistry.java:83)
	at org.terracotta.management.entity.tms.server.TmsAgentEntityServerService.createPassiveEntity(TmsAgentEntityServerService.java:63)
	at org.terracotta.management.entity.tms.server.TmsAgentEntityServerService.createPassiveEntity(TmsAgentEntityServerService.java:42)
	at org.terracotta.voltron.proxy.server.ProxyServerEntityService.createPassiveEntity(ProxyServerEntityService.java:113)
	at org.terracotta.voltron.proxy.server.ProxyServerEntityService.createPassiveEntity(ProxyServerEntityService.java:38)
	at org.terracotta.passthrough.PassthroughServerProcess$CreationData.<init>(PassthroughServerProcess.java:1162)
	at org.terracotta.passthrough.PassthroughServerProcess.createAndStoreEntity(PassthroughServerProcess.java:1115)
	at org.terracotta.passthrough.PassthroughServerProcess.create(PassthroughServerProcess.java:707)
	at org.terracotta.passthrough.PassthroughServerMessageDecoder.decode(PassthroughServerMessageDecoder.java:344)
	at org.terracotta.passthrough.PassthroughServerMessageDecoder.decode(PassthroughServerMessageDecoder.java:37)
	at org.terracotta.passthrough.PassthroughMessageCodec.runRawDecoder(PassthroughMessageCodec.java:344)
	at org.terracotta.passthrough.PassthroughMessageCodec.decodeRawMessage(PassthroughMessageCodec.java:267)
	at org.terracotta.passthrough.PassthroughServerProcess.serverThreadHandleMessage(PassthroughServerProcess.java:508)
	at org.terracotta.passthrough.PassthroughServerProcess.runServerThread(PassthroughServerProcess.java:484)
	at org.terracotta.passthrough.PassthroughServerProcess.access$000(PassthroughServerProcess.java:80)
	at org.terracotta.passthrough.PassthroughServerProcess$2.run(PassthroughServerProcess.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mathieucarbou** [comment]
What did you do to get this exception @myronkscott ? When I run the test, I see no stack trace at all in the console or logs... Is there a DEBUG mode for passthrough ? Does passthrough hides some exceptions ?
